<?php

namespace BenSherred\MakeModel\Commands;

use Illuminate\Filesystem\Filesystem;
use Illuminate\Foundation\Console\ModelMakeCommand;

class MakeModelCommand extends ModelMakeCommand
{
    public function __construct(Filesystem $files)
    {
        parent::__construct($files);
    }

    public function handle()
    {
        return parent::handle(); // TODO: Change the autogenerated stub
    }
}
